apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ca-central-1

nodeGroups:
  - name: master-group
    instanceType: t2.micro
    desiredCapacity: 1

  - name: worker-group
    instanceType: t2.micro
    desiredCapacity: 1
