apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    env  : prod
    owner: Maksim_Strekalov
spec:
  selector:
    project: Kefir_project 
  ports:
    - name      : 80-port
      protocol  : TCP
      port      : 80  
      targetPort: 80  
  type: LoadBalancer
